# Advanced Pandas

***

Author: Jiacheng

Date: 2019-05-21

***

In [1]:
import numpy as np
import pandas as pd

---

## 1. Categorical Data
## 分类数据

In [2]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [3]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [4]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [5]:
values = pd.Series([0, 1, 0, 0] * 2)
dim = pd.Series(['apple', 'orange'])
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [6]:
dim

0     apple
1    orange
dtype: object

In [7]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

* ### pandas的分类类型

In [8]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': np.random.randint(3, 15, size=N),
                   'weight': np.random.uniform(0, 4, size=N)},
                   columns=['basket_id', 'fruit', 'count', 'weight'])
df


basket_id   fruit  count    weight
0          0   apple      4  1.359555
1          1  orange     10  0.304966
2          2   apple      5  3.241258
3          3   apple      6  0.182192
4          4   apple     12  0.124833
5          5  orange      5  0.744314
6          6   apple      4  0.128083
7          7   apple      9  3.207090

In [10]:
fruit_cat = df['fruit']
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: object

In [11]:
# 转换为category
fruit_cat = df['fruit'].astype('category')
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [12]:
# 不是NumPy数组，而是一个pandas.Categorical实例：
type(fruit_cat.values)

pandas.core.arrays.categorical.Categorical

In [13]:
fruit_cat.values.categories

Index(['apple', 'orange'], dtype='object')

In [14]:
fruit_cat.values.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [15]:
df.fruit = fruit_cat
df.fruit

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): [apple, orange]

In [16]:
# 创建categorical
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
my_categories

[foo, bar, baz, foo, bar]
Categories (3, object): [bar, baz, foo]

In [17]:
# 通过列表创建categories
# 标签对应分类
categories = ['foo', 'bar', 'baz']
codes = [0, 1, 2, 0, 0, 1]
my_cats_2 = pd.Categorical.from_codes(codes, categories)
my_cats_2

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo, bar, baz]

In [18]:
# 指定顺序(通过codes)
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)
ordered_cat

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo < bar < baz]

In [19]:
my_cats_2.as_ordered()

[foo, bar, baz, foo, foo, bar]
Categories (3, object): [foo < bar < baz]

* ### 用分类进行计算

In [20]:
np.random.seed(12345)
draws = np.random.randn(1000)
draws[:10]

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474])

In [22]:
bins = pd.qcut(draws, 4)
bins

[(-0.684, -0.0101], (-0.0101, 0.63], (-0.684, -0.0101], (-0.684, -0.0101], (0.63, 3.928], ..., (-0.0101, 0.63], (-0.684, -0.0101], (-2.9499999999999997, -0.684], (-0.0101, 0.63], (0.63, 3.928]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -0.684] < (-0.684, -0.0101] < (-0.0101, 0.63] < (0.63, 3.928]]

In [23]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
bins

[Q2, Q3, Q2, Q2, Q4, ..., Q3, Q2, Q1, Q3, Q4]
Length: 1000
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [24]:
bins.codes[:10]

array([1, 2, 1, 1, 3, 3, 2, 2, 3, 3], dtype=int8)

In [25]:
bins.categories

Index(['Q1', 'Q2', 'Q3', 'Q4'], dtype='object')

In [28]:
bins = pd.Series(bins, name='quartile')
bins

0      Q2
1      Q3
2      Q2
3      Q2
4      Q4
5      Q4
6      Q3
7      Q3
8      Q4
9      Q4
10     Q4
11     Q1
12     Q3
13     Q3
14     Q4
15     Q4
16     Q1
17     Q2
18     Q4
19     Q2
20     Q2
21     Q3
22     Q4
23     Q1
24     Q2
25     Q3
26     Q3
27     Q3
28     Q3
29     Q4
       ..
970    Q2
971    Q1
972    Q2
973    Q4
974    Q3
975    Q1
976    Q1
977    Q2
978    Q2
979    Q3
980    Q3
981    Q1
982    Q3
983    Q4
984    Q2
985    Q4
986    Q1
987    Q4
988    Q1
989    Q3
990    Q1
991    Q4
992    Q1
993    Q4
994    Q2
995    Q3
996    Q2
997    Q1
998    Q3
999    Q4
Name: quartile, Length: 1000, dtype: category
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [27]:
results = (pd.Series(draws).groupby(bins).agg(['count', 'min', 'max']).reset_index())
results


quartile  count       min       max
0       Q1    250 -2.949343 -0.685484
1       Q2    250 -0.683066 -0.010115
2       Q3    250 -0.010032  0.628894
3       Q4    250  0.634238  3.927528

In [29]:
# 分位数保存原始的面元分类信息
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

* ### 用分类提高性能

In [30]:
N = 10000000
draws = pd.Series(np.random.randn(N))
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [39]:
categories = labels.astype('category')
categories

0          foo
1          bar
2          baz
3          qux
4          foo
5          bar
6          baz
7          qux
8          foo
9          bar
10         baz
11         qux
12         foo
13         bar
14         baz
15         qux
16         foo
17         bar
18         baz
19         qux
20         foo
21         bar
22         baz
23         qux
24         foo
25         bar
26         baz
27         qux
28         foo
29         bar
          ... 
9999970    baz
9999971    qux
9999972    foo
9999973    bar
9999974    baz
9999975    qux
9999976    foo
9999977    bar
9999978    baz
9999979    qux
9999980    foo
9999981    bar
9999982    baz
9999983    qux
9999984    foo
9999985    bar
9999986    baz
9999987    qux
9999988    foo
9999989    bar
9999990    baz
9999991    qux
9999992    foo
9999993    bar
9999994    baz
9999995    qux
9999996    foo
9999997    bar
9999998    baz
9999999    qux
Length: 10000000, dtype: category
Categories (4, object): [bar, baz, foo, qux]

In [40]:
labels.memory_usage()

80000080

In [41]:
categories.memory_usage()

10000272

In [42]:
%time _ = labels.astype('category')

CPU times: user 299 ms, sys: 57.2 ms, total: 356 ms
Wall time: 355 ms


* ### 分类方法

In [43]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)
cat_s = s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): [a, b, c, d]

In [44]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [45]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [47]:
# 重新设定分类
actual_categories = ['a', 'b', 'c', 'd', 'e']
cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): [a, b, c, d, e]

In [48]:
cat_s.value_counts()

d    2
c    2
b    2
a    2
dtype: int64

In [49]:
cat_s2.value_counts()

d    2
c    2
b    2
a    2
e    0
dtype: int64

In [50]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): [a, b, c, d]

In [51]:
# 删除看不到的分类
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): [a, b]

* ### 为建模创建虚拟变量

In [52]:
# 列包含给定分类的1，其它为0
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [53]:
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1

---

## 2. Advanced GroupBy Use
## GroupBy高级应用

* ### 分组转换和“解封”GroupBy

In [55]:
df = pd.DataFrame({'key': ['a', 'b', 'c'] * 4,
                   'value': np.arange(12.)})
df

key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [57]:
g = df.groupby('key').value
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [58]:
g.transform(lambda x: x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [61]:
g.apply(lambda x: x.mean())

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [62]:
# 内置聚合函数，传递字符串
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [69]:
g.transform(lambda x: x * 2)

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
11    22.0
Name: value, dtype: float64

In [70]:
g.transform(lambda x: x.rank(ascending=False))

0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64

In [71]:
def normalize(x):
    return (x - x.mean()) / x.std()

In [72]:
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [73]:
g.apply(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [74]:
# 解封操作，速度更快
normalized = (df['value'] - g.transform('mean')) / g.transform('std')
normalized

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

* ### 分组的时间重采样

In [75]:
N = 15
times = pd.date_range('2019-05-21 00:00', freq='1min', periods=N)
df = pd.DataFrame({'time': times, 'value': np.arange(N)})
df

time  value
0  2019-05-21 00:00:00      0
1  2019-05-21 00:01:00      1
2  2019-05-21 00:02:00      2
3  2019-05-21 00:03:00      3
4  2019-05-21 00:04:00      4
5  2019-05-21 00:05:00      5
6  2019-05-21 00:06:00      6
7  2019-05-21 00:07:00      7
8  2019-05-21 00:08:00      8
9  2019-05-21 00:09:00      9
10 2019-05-21 00:10:00     10
11 2019-05-21 00:11:00     11
12 2019-05-21 00:12:00     12
13 2019-05-21 00:13:00     13
14 2019-05-21 00:14:00     14

In [76]:
df.set_index('time').resample('5min').count()

value
time                      
2019-05-21 00:00:00      5
2019-05-21 00:05:00      5
2019-05-21 00:10:00      5

In [78]:
df2 = pd.DataFrame({'time': times.repeat(3),
                    'key': np.tile(['a', 'b', 'c'], N),
                    'value': np.arange(N * 3.)})
df2[:15]

time key  value
0  2019-05-21 00:00:00   a    0.0
1  2019-05-21 00:00:00   b    1.0
2  2019-05-21 00:00:00   c    2.0
3  2019-05-21 00:01:00   a    3.0
4  2019-05-21 00:01:00   b    4.0
5  2019-05-21 00:01:00   c    5.0
6  2019-05-21 00:02:00   a    6.0
7  2019-05-21 00:02:00   b    7.0
8  2019-05-21 00:02:00   c    8.0
9  2019-05-21 00:03:00   a    9.0
10 2019-05-21 00:03:00   b   10.0
11 2019-05-21 00:03:00   c   11.0
12 2019-05-21 00:04:00   a   12.0
13 2019-05-21 00:04:00   b   13.0
14 2019-05-21 00:04:00   c   14.0

In [80]:
time_key = pd.Grouper(freq='5min')
resampled = (df2.set_index('time')
             .groupby(['key', time_key])
             .sum())
resampled

value
key time                      
a   2019-05-21 00:00:00   30.0
    2019-05-21 00:05:00  105.0
    2019-05-21 00:10:00  180.0
b   2019-05-21 00:00:00   35.0
    2019-05-21 00:05:00  110.0
    2019-05-21 00:10:00  185.0
c   2019-05-21 00:00:00   40.0
    2019-05-21 00:05:00  115.0
    2019-05-21 00:10:00  190.0

---

## 3. Techniques for Method Chaining
## 链式编程技术

* ### 管道方法